### ISSUE TITLE
Document what to do in case of issues

### ISSUE THREAD

**Issue by JakeDawkins** [apollographql/orbiter#13]
Runbook:
- broken builds on rover, meaning most recent release can't be used
- Github down?
-

**Comment by EverlastingBugstopper** [comment]
I'm hoping we don't run in to a scenario where we produce a broken build with Rover, especially since everything is in CI. If it's released, it's released, and if it's broken we need to release a new fixed version. Don't think orbiter needs to be concerned with that scenario tbh

**Comment by JakeDawkins** [comment]
@EverlastingBugstopper haven't the past couple releases been perfect cases of why we do need this though? The last 2 releases have been released and in a partially unusable state for some time right?

**Comment by EverlastingBugstopper** [comment]
Sure! but we solved that in the same way I'd think we did that in the future, which is by fixing the bugs and cutting a new release. once you've tagged a version and made a release, it's out there and theres not too many takes backsies other then just fixing it quick and bumping the version

**Comment by JakeDawkins** [comment]
explicit versioning in the url seems like the best thing here, we could even do a `/latest` to always download the latest, so it's explicit
