### ISSUE TITLE
add router download functionality

### ISSUE THREAD

**Issue by abernix** [apollographql/orbiter#41]
This relates closely to the implementation of what is being asked in https://github.com/apollographql/router/issues/962.

Copying that content here for scope:

> Right now we have this on [our quick start](https://www.apollographql.com/docs/router/quickstart) docs:
> 
> ```shell
> bash <(curl -fsSL https://raw.githubusercontent.com/apollographql/router/main/scripts/install.sh)
> ```
> 
> Whereas [Rover's docs](https://www.apollographql.com/docs/rover/getting-started) have something like this:
> 
> ```shell
> curl -sSL https://rover.apollo.dev/nix/latest | sh
> ```
> 
> and the ability to install _specific_ versions via
> 
> ```shell
> curl -sSL https://rover.apollo.dev/nix/v0.5.1 | sh
> ```
> 
> We may want to have a similar `router.apollo.dev` redirect, which we could accomplish through the [same `orbiter` repo functionality](https://github.com/apollographql/orbiter/). This would also give us the ability to mitigate an outage on GitHub.

**Comment by abernix** [comment]
Since the Router's current script doesn't *install* in the same way as `rover` does (the installer in `router` only **downloads** it to the current working directory) I'm tempted to suggest we do something **almost identical** to the Rover pattern with a `/download/` variation to it.

So, for the purposes of a straw-dog, the URLs could look like:

```bash
https://router.apollo.dev/download/nix/v0.9.0
```

or

```bash
https://router.apollo.dev/download/nix/latest
```

**Comment by abernix** [comment]
Tied up in this question is an implementation detail about the suggested usage pattern — the approach chosen by Router (in the documentation, at the moment) seems to be to spawn a sub-shell and redirect back into `bash`.  I'm curious about details as to our use of that approach versus the approach that Rover had committed to previously.  It looks like it was introduced into the documentation as part of a larger approach in https://github.com/apollographql/router/pull/820/files#diff-4eb6b815edfd1eeb62a9234fd1c7dffb687ccc6e99f3a978574962c77ed25fa3R12-R15, though that was of course a stop-gap approach, so not sure if there was anything in particular motivating about it other than getting it done and over the line for the preview release 😉 .

**In principle**, I'd like us aligned on that pattern, but we could diverge with intent!

(It's also worth noting that in Rover's case, it was _very_ intentional to be entirely POSIX-compatible and not require `bash`)

**Comment by abernix** [comment]
Perhaps @BrynCooke could enlighten us when given a moment. 😜

**Comment by BrynCooke** [comment]
There was no reason for the current functionality other than we just wanted to do something. and it was quick to implement.
I like way that Rover downloads are handled.
