### ISSUE TITLE
error: HTTP status server error (502 Bad Gateway) for supergraph url 

### ISSUE THREAD

**Issue by prasek** [apollographql/orbiter#54]
## Description

Got a 502 during [nightly CI ](https://github.com/apollographql/supergraph-demo-fed2/actions/runs/3117127556/jobs/5055557960#step:6:13)

Seems to be intermittent.

### Steps to reproduce

https://github.com/apollographql/supergraph-demo-fed2/blob/main/.github/workflows/local-router-rust-main.yaml

```
+ cd examples/local/supergraph
+ rover supergraph compose --elv2-license=accept --config localhost.yaml
installing plugin 'supergraph-2' for 'rover supergraph compose'...
downloading supergraph from https://rover.apollo.dev/tar/supergraph/x86_64-unknown-linux-gnu/latest-2
```

### Expected result

No 502

### Actual result

```
[502](error: HTTP status server error (502 Bad Gateway) for url (https://rover.apollo.dev/tar/supergraph/x86_64-unknown-linux-gnu/latest-2))
```

### Environment

Rover Info:
Version: 0.9.0
Install Location: /home/runner/.rover/bin/rover
OS: Ubuntu 20.04 (focal) [64-bit]
Shell: Unknown

From [here](https://github.com/apollographql/supergraph-demo-fed2/actions/runs/3117127556/jobs/5055557960#step:5:7).

**Comment by abernix** [comment]
Going to close this, but happy to reopen if the intermittence returns.
